---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yaml

  roles:
    # - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: zsh_setup
    - role: dotfiles
    # - role: geerlingguy.dotfiles
    #   when: configure_dotfiles
    #   tags: ['dotfiles']
    # - role: geerlingguy.mac.mas
    #   when: mas_installed_apps or mas_installed_app_ids
    #   tags: ['mas']
    # - role: geerlingguy.mac.dock
    #   when: configure_dock
    #   tags: ['dock']

  tasks:
    - name: Clone Neovim config repo
      ansible.builtin.git:
        repo: "https://github.com/anazworth/Neovim-Curry.git"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        version: main
        update: true
