---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yaml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: zsh_setup
    - role: dotfiles

  tasks:
    - name: Clone Neovim config repo
      ansible.builtin.git:
        repo: "https://github.com/anazworth/Neovim-Curry.git"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        version: main
        update: true
