---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "https://github.com/anazworth/.dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    version: main
    update: true

- name: Run stow for selected dotfiles
  ansible.builtin.shell: |
    stow -t ~/ ideavim tmux wallpapers wezterm ghostty
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles"
